version: 2
updates:
  - package-ecosystem: bundler
    directory: /hafapass_api
    schedule:
      interval: weekly
    groups:
      ruby-dependencies:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /hafapass_frontend
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
