source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "dotenv-rails"
gem "jwt"
gem "stripe"
gem "aws-sdk-s3"
gem "resend"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# Background jobs
gem "sidekiq", "~> 7.0"
gem "redis", "~> 5.0"

# Rate limiting
gem "rack-attack", "~> 6.7"

# Pagination
gem "pagy", "~> 9.0"

# PDF generation
gem "prawn", "~> 2.5"
gem "prawn-table", "~> 0.2"
gem "rqrcode", "~> 2.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
end
